--
-- PostgreSQL database dump
--

\restrict 6OsyhrV8DvJxHVn1sJ8zhVtztnRn5aaoO3vK03ZBbRZ0ae55QgqunPyjoJHzgJT

-- Dumped from database version 18.4
-- Dumped by pg_dump version 18.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: categoria; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.categoria (
    id_categoria integer NOT NULL,
    nome character varying(100) NOT NULL,
    tipo character varying(10) NOT NULL,
    CONSTRAINT chk_categoria_tipo CHECK (((tipo)::text = ANY ((ARRAY['RECEITA'::character varying, 'DESPESA'::character varying])::text[])))
);


ALTER TABLE public.categoria OWNER TO postgres;

--
-- Name: categoria_id_categoria_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.categoria ALTER COLUMN id_categoria ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.categoria_id_categoria_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: despesa; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.despesa (
    id_despesa bigint NOT NULL,
    descricao text NOT NULL,
    valor numeric(10,2) NOT NULL,
    data timestamp without time zone NOT NULL,
    recorrencia character varying(20) NOT NULL,
    id_usuario bigint NOT NULL,
    id_categoria integer NOT NULL,
    status character varying(20) NOT NULL,
    CONSTRAINT chk_despesa_recorrencia CHECK (((recorrencia)::text = ANY ((ARRAY['FIXA'::character varying, 'TEMPORARIA'::character varying])::text[]))),
    CONSTRAINT chk_despesa_status CHECK (((status)::text = ANY ((ARRAY['PAGA'::character varying, 'PENDENTE'::character varying, 'AGENDADA'::character varying])::text[])))
);


ALTER TABLE public.despesa OWNER TO postgres;

--
-- Name: despesa_id_despesa_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.despesa ALTER COLUMN id_despesa ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.despesa_id_despesa_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: meta; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.meta (
    id bigint NOT NULL,
    data_limite date NOT NULL,
    id_usuario bigint,
    nome character varying(200) NOT NULL,
    valor_contribuido numeric(10,2) NOT NULL,
    valor_objetivo numeric(10,2) NOT NULL,
    CONSTRAINT meta_valor_contribuido_check CHECK ((valor_contribuido >= (0)::numeric)),
    CONSTRAINT meta_valor_objetivo_check CHECK ((valor_objetivo >= (0)::numeric))
);


ALTER TABLE public.meta OWNER TO postgres;

--
-- Name: meta_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.meta ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.meta_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: receita; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.receita (
    id_receita bigint NOT NULL,
    descricao text NOT NULL,
    valor numeric(10,2) NOT NULL,
    data timestamp without time zone NOT NULL,
    recorrencia character varying(20) NOT NULL,
    id_usuario bigint NOT NULL,
    id_categoria integer NOT NULL,
    CONSTRAINT chk_receita_recorrencia CHECK (((recorrencia)::text = ANY ((ARRAY['FIXA'::character varying, 'TEMPORARIA'::character varying])::text[])))
);


ALTER TABLE public.receita OWNER TO postgres;

--
-- Name: receita_id_receita_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.receita ALTER COLUMN id_receita ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.receita_id_receita_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: telefone_usuario; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.telefone_usuario (
    id_telefone bigint NOT NULL,
    numero character varying(15) NOT NULL,
    id_usuario bigint NOT NULL
);


ALTER TABLE public.telefone_usuario OWNER TO postgres;

--
-- Name: telefone_usuario_id_telefone_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.telefone_usuario_id_telefone_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.telefone_usuario_id_telefone_seq OWNER TO postgres;

--
-- Name: telefone_usuario_id_telefone_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.telefone_usuario_id_telefone_seq OWNED BY public.telefone_usuario.id_telefone;


--
-- Name: usuario; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuario (
    id_usuario bigint NOT NULL,
    email character varying(255) NOT NULL,
    senha_hash character varying(255) NOT NULL,
    data_criacao timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    nome character varying(100)
);


ALTER TABLE public.usuario OWNER TO postgres;

--
-- Name: usuario_id_usuario_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.usuario_id_usuario_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.usuario_id_usuario_seq OWNER TO postgres;

--
-- Name: usuario_id_usuario_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.usuario_id_usuario_seq OWNED BY public.usuario.id_usuario;


--
-- Name: telefone_usuario id_telefone; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.telefone_usuario ALTER COLUMN id_telefone SET DEFAULT nextval('public.telefone_usuario_id_telefone_seq'::regclass);


--
-- Name: usuario id_usuario; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario ALTER COLUMN id_usuario SET DEFAULT nextval('public.usuario_id_usuario_seq'::regclass);


--
-- Name: categoria categoria_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categoria
    ADD CONSTRAINT categoria_pkey PRIMARY KEY (id_categoria);


--
-- Name: despesa despesa_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.despesa
    ADD CONSTRAINT despesa_pkey PRIMARY KEY (id_despesa);


--
-- Name: meta meta_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.meta
    ADD CONSTRAINT meta_pkey PRIMARY KEY (id);


--
-- Name: receita receita_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.receita
    ADD CONSTRAINT receita_pkey PRIMARY KEY (id_receita);


--
-- Name: telefone_usuario telefone_usuario_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.telefone_usuario
    ADD CONSTRAINT telefone_usuario_pkey PRIMARY KEY (id_telefone);


--
-- Name: usuario usuario_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_email_key UNIQUE (email);


--
-- Name: usuario usuario_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_pkey PRIMARY KEY (id_usuario);


--
-- Name: despesa fk_despesa_categoria; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.despesa
    ADD CONSTRAINT fk_despesa_categoria FOREIGN KEY (id_categoria) REFERENCES public.categoria(id_categoria);


--
-- Name: despesa fk_despesa_usuario; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.despesa
    ADD CONSTRAINT fk_despesa_usuario FOREIGN KEY (id_usuario) REFERENCES public.usuario(id_usuario) ON DELETE CASCADE;


--
-- Name: receita fk_receita_categoria; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.receita
    ADD CONSTRAINT fk_receita_categoria FOREIGN KEY (id_categoria) REFERENCES public.categoria(id_categoria);


--
-- Name: receita fk_receita_usuario; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.receita
    ADD CONSTRAINT fk_receita_usuario FOREIGN KEY (id_usuario) REFERENCES public.usuario(id_usuario) ON DELETE CASCADE;


--
-- Name: telefone_usuario fk_usuario_telefone; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.telefone_usuario
    ADD CONSTRAINT fk_usuario_telefone FOREIGN KEY (id_usuario) REFERENCES public.usuario(id_usuario) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict 6OsyhrV8DvJxHVn1sJ8zhVtztnRn5aaoO3vK03ZBbRZ0ae55QgqunPyjoJHzgJT

